/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bottom: typeof import('./src/components/index/Bottom.vue')['default']
    BottomList: typeof import('./src/components/home/BottomList.vue')['default']
    Header: typeof import('./src/components/index/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RightList: typeof import('./src/components/home/RightList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/home/Swiper.vue')['default']
  }
}
