/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[…404]': RouteRecordInfo<'/[…404]', '/:…404', { …404: ParamValue<true> }, { …404: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/medicine-web': RouteRecordInfo<'/medicine-web', '/medicine-web', Record<never, never>, Record<never, never>>,
    '/medicine-web/assess': RouteRecordInfo<'/medicine-web/assess', '/medicine-web/assess', Record<never, never>, Record<never, never>>,
    '/medicine-web/audio': RouteRecordInfo<'/medicine-web/audio', '/medicine-web/audio', Record<never, never>, Record<never, never>>,
    '/medicine-web/book': RouteRecordInfo<'/medicine-web/book', '/medicine-web/book', Record<never, never>, Record<never, never>>,
    '/medicine-web/consult': RouteRecordInfo<'/medicine-web/consult', '/medicine-web/consult', Record<never, never>, Record<never, never>>,
    '/medicine-web/home': RouteRecordInfo<'/medicine-web/home', '/medicine-web/home', Record<never, never>, Record<never, never>>,
    '/medicine-web/indep/quiz': RouteRecordInfo<'/medicine-web/indep/quiz', '/medicine-web/indep/quiz', Record<never, never>, Record<never, never>>,
    '/medicine-web/information': RouteRecordInfo<'/medicine-web/information', '/medicine-web/information', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal': RouteRecordInfo<'/medicine-web/personal', '/medicine-web/personal', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/answer': RouteRecordInfo<'/medicine-web/personal/answer', '/medicine-web/personal/answer', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/browsing': RouteRecordInfo<'/medicine-web/personal/browsing', '/medicine-web/personal/browsing', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/collection': RouteRecordInfo<'/medicine-web/personal/collection', '/medicine-web/personal/collection', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/edit': RouteRecordInfo<'/medicine-web/personal/edit', '/medicine-web/personal/edit', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/logout': RouteRecordInfo<'/medicine-web/personal/logout', '/medicine-web/personal/logout', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/quiz': RouteRecordInfo<'/medicine-web/personal/quiz', '/medicine-web/personal/quiz', Record<never, never>, Record<never, never>>,
    '/medicine-web/personal/stact': RouteRecordInfo<'/medicine-web/personal/stact', '/medicine-web/personal/stact', Record<never, never>, Record<never, never>>,
    '/medicine-web/practice': RouteRecordInfo<'/medicine-web/practice', '/medicine-web/practice', Record<never, never>, Record<never, never>>,
    '/medicine-web/special': RouteRecordInfo<'/medicine-web/special', '/medicine-web/special', Record<never, never>, Record<never, never>>,
    '/medicine-web/test/quiz': RouteRecordInfo<'/medicine-web/test/quiz', '/medicine-web/test/quiz', Record<never, never>, Record<never, never>>,
    '/medicine-web/video': RouteRecordInfo<'/medicine-web/video', '/medicine-web/video', Record<never, never>, Record<never, never>>,
  }
}
